__use_yte__: true

default-resources:
    runtime: 1h
    mem_mb: 1024
    disk_mb: 1 * 1024

set-threads:
    # reads
    # reference
    reference__recompress__genome: 8
    reference__recompress__vcf: 8
    reference__recompress__gtf: 8
    # align
    align__index__: 8
    align__map__: 24
    align__mark_duplicates__: 0  # pipe!
    align__mark_duplicates__bam_to_cram__: 24
    align__recalibrate__bam_to_cram__: 24
    # genotype
    genotype__variant_filtration__merge__: 24
    # annotate
    # swaps
    # report


set-resources:
    # helpers
    # reads
    # reference
    reference__recompress__gtf:
        mem_mb: 4G
    # align
    align__index__:
        mem_mb: 64G
        runtime: 1d
    align__map__:
        mem_mb: 64G
        runtime: 1d
    align__mark_duplicates__:
        mem_mb: 8G
        runtime: 6h
    align__mark_duplicates__bam_to_cram__:
        mem_mb: 8G  # this must match align__mark_duplicates__
        runtime: 12h
    align__bcftools__call__:
        mem_mb: 8G
        runtime: 1d
    align__recalibrate__baserecalibrator__:
        mem_mb: 8G
        runtime: 1d
    align__recalibrate__applybqsr__:
        mem_mb: 8G
        runtime: 1d
    align__recalibrate__bam_to_cram__:
        mem_mb: 8G  # this should match align__recalibrate__applybqsr__
        runtime: 6h
    # variants
    variants__call__haplotype_caller__:
        mem_mb: 8G
        runtime: 1d
    variants__call__combine_gvcfs__:
        mem_mb: 8G
        runtime: 1d
    variants__genotype__genotype_gvcfs__:
        mem_mb: 8G
        runtime: 1d
    # annotate
    annotate__snpeff__annotate__:
        mem_mb: 8G
        runtime: 1d
    annotate__vep__:
        mem_mb: 8G
        runtime: 4h
    # swaps
    swaps__somalier__find_sites__:
        mem_mb: 8G
    # report
