__use_yte__: true

default-resources:
    runtime: 60
    mem_mb: 1024

set-threads:


set-resources:
    # variants
    variants__genotype__genotype_gvcfs:
        mem_mb: 8 * 1024
        runtime: 24 * 60
    # annotate
    annotate__vep:
        mem_mb: 16 * 1024
        runtime: 8 * 60
    # swaps
    swaps__somalier__find_sites:
        mem_mb: 16 * 1024
    # report
