__use_yte__: true

default-resources:
    runtime: 60
    mem_mb: 1024

set-threads:
    # reference
    reference__recompress__genome: 8
    reference__recompress__vcf: 8
    reference__recompress__gtf: 8
    # align
    align__bwamem2__index: 8
    align__bwamem2__map: 24
    align__mark_duplicates: 0  # pipe!
    align__mark_duplicates__bam_to_cram: 24
    align__recalibrate__applybqsr: 0
    align__recalibrate__bam_to_cram: 24
    # annotate
    # swaps
    # report


set-resources:
    # reference
    reference__recompress__gtf:
        mem_mb: 4G
    # align
    align__bwamem2__index:
        mem_mb: 64 * 1024
        runtime: 24 * 60
    align__bwamem2__map:
        mem_mb: 64 * 1024
        runtime: 24 * 60
    align__mark_duplicates:
        mem_mb: 8 * 1024
        runtime: 6 * 60
    align__bcftools__call:
        mem_mb: 8 * 1024
        runtime: 24 * 60
    align__recalibrate__baserecalibrator:
        mem_mb: 8 * 1024
        runtime: 24 * 60
    align__recalibrate__applybqsr:
        mem_mb: 8 * 1024
        runtime: 24 * 60
    align__recalibrate__bam_to_cram:
        mem_mb: 8 * 1024
        runtime: 6 * 60
    align__multiqc:
        mem_mb: 8 * 1024
        runtime: 6 * 60
    # variants
    variants__call__haplotype_caller:
        mem_mb: 8 * 1024
        runtime: 24 * 60
    variants__call__combine_gvcfs:
        mem_mb: 16 * 1024
        runtime: 24 * 60
    variants__genotype__genotype_gvcfs:
        mem_mb: 8 * 1024
        runtime: 24 * 60
    # annotate
    annotate__vep:
        mem_mb: 16 * 1024
        runtime: 8 * 60
    # swaps
    swaps__somalier__find_sites:
        mem_mb: 16 * 1024
    # report
