reference:
    dna: resources/reference/ggal.mock.fa.gz
    known_vcf: resources/reference/ggal.mock.vcf.gz
    autosomes: [1, 2]
    male_chromosomes: [Z, W]
    female_chromosomes: [Z]
    mitochondria: [MT]

snpeff:
    genome:
        - GRCg6a.105
