reference:
    dna: resources/reference/ggal.mock.fa.gz
    known_vcf: resources/reference/ggal.mock.vcf.gz
    regions: resources/reference/ggal.mock.bed4
    # autosomes: [1, 2]
    male_chromosomes: [Z]  # [X, Y]
    female_chromosomes: [Z,W]  # [X]
    mitochondria: [MT]

snpeff:
    genome:
        - GRCg6a.105
