

align:
  bwamem2:
    extra: ""


picard:

variants:
  filter:
    SNP: "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0"
    INDEL: "QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0"

snpeff:
