# Cache .snakemake/conda each sunday / monday night
---
# name: Cache conda packages weekly
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '@weekly'
  workflow_dispatch:

jobs:
  weekly-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: .snakemake/conda
          key: snakemake-conda-${{ env.CACHE_NUMBER }}
        id: cache
      - name: Download environments
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: >
            --use-conda
            --conda-create-envs-only
            --conda-frontend mamba
            --cores 1



# jobs:
#   Caching:
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v3
#     - name:

#   my-job:
#     name: Delete all caches
#     runs-on: ubuntu-20.04

#     steps:
#       - name: Clear caches
#         uses: easimon/wipe-cache@main
#         with:
#           dry-run: 'true'
